---
- hosts: app
  become: yes
  gather_facts: no
  tasks:
    - name: get ads container id
      shell: docker inspect --format='{{.Id}}' ads
      register: ads_container_id
    - name: get auth container id
      shell: docker inspect --format='{{.Id}}' auth
      register: auth_container_id
    - name: prepare filebeat config
      delegate_to: localhost
      template:
        src: ../filebeat/filebeat.j2
        dest: ../filebeat/filebeat.yml
    - name: run docket compose
      docker_compose:
        project_name: ads
        definition:
          version: '3'
          services:
            rabbitmq:
              image: rabbitmq:3-management
              container_name: rabbitmq
              hostname: node1
              ports:
                - 5672:5672
                - 15672:15672
              volumes:
                - rabbitmq:/var/lib/rabbitmq
            filebeat:
              image: docker.elastic.co/beats/filebeat-oss:7.8.0
              container_name: filebeat
              depends_on:
                - elasticsearch
              volumes:
                - filebeat:/usr/share/filebeat/data
                - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            elasticsearch:
              image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
              container_name: elasticsearch
              volumes:
                - elasticsearch:/usr/share/elasticsearch/data
                - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            kibana:
              image: docker.elastic.co/kibana/kibana-oss:7.8.0
              container_name: kibana
              depends_on:
                - elasticsearch
              environment: 
                ELASTICSEARCH_HOSTS: http://elasticsearch:9200
              ports:
                - 5601:5601
            logstash:
              image: docker.elastic.co/logstash/logstash-oss:7.8.0
              container_name: logstash
              depends_on:
                - elasticsearch
              ports:
                - 5044:5044
              volumes:
                - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
          volumes:
            rabbitmq:
            filebeat:
            elasticsearch:


