---
- hosts: db
  become: yes
  gather_facts: no

  tasks:
    - name: ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name : ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2

- hosts: db
  become: yes
  become_user: root
  gather_facts: no
  vars:
    ads_db: ads_microservice_production
    ads_user: ads
    auth_db: auth_microservice_production
    auth_user: auth
    password: password
  
  tasks:
    - name: ensure ads_microservice_production db is created
      postgresql_db:
        name: '{{ads_db}}'
    
    - name: ensure user has access to db
      postgresql_user:
        db: '{{ads_db}}'
        name: '{{ads_user}}'
        password: '{{password}}'
        priv: ALL

    - name: ensure user has no extra privs
      postgresql_user:
        name: '{{ads_user}}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB

    - name: ensure no other user can access db
      postgresql_privs:
        db: '{{ads_db}}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent

    - name: ensure auth_microservice_production db is created
      postgresql_db:
        name: '{{auth_db}}'
    
    - name: ensure user has access to db
      postgresql_user:
        db: '{{auth_db}}'
        name: '{{auth_user}}'
        password: '{{password}}'
        priv: ALL

    - name: ensure user has no extra privs
      postgresql_user:
        name: '{{auth_user}}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB

    - name: ensure no other user can access db
      postgresql_privs:
        db: '{{auth_db}}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
     
     
